services:
    server:
        image: node:18
        container_name: Chatbox-server
        ports:
            - "8080:8080"
        working_dir: /server
        command: sh -c "npm install && npx ts-node src/server.ts"
        volumes:
            - ./server:/server
            - ./server/data:/server/data
        networks:
            - chat-net
        stop_grace_period: 1s

    client:
        image: node:18-alpine
        container_name: Chatbox-client
        ports:
            - "5173:5173"
        working_dir: /client
        command: sh -c "npm install && npm run dev"
        volumes:
            - ./client:/client
        networks:
            - chat-net
        stop_grace_period: 1s
networks:
    chat-net:
